== Normative references

The following referenced documents are indispensable for the application of this specification.
For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document applies.


[IEEE P2874]
Draft Standard for Spatial Web Protocol, Architecture, and Governance.


[W3C did-core], Decentralized Identifiers (DIDs) v1.0

[W3C did-spec-registries]

[W3C json-ld11], A JSON-based Serialization for Linked Data

[W3C json-ld11]
JSON-LD 1.1: A JSON-based Serialization for Linked Data, W3C Recommendation.

[W3C RDF11 Concepts]
RDF 1.1 Concepts and Abstract Syntax, W3C Recommendation.

[W3C RDF12 Concepts]
RDF 1.2 Concepts and Abstract Syntax, W3C Working Draft.

[W3C RDF12 Turtle]
RDF 1.2 Turtle, W3C Working Draft.

[W3C RDF12 Semantics]
RDF 1.2 Semantics, W3C Working Draft.

[W3C RDF-star]
RDF-star and SPARQL-star, W3C Candidate Recommendation.

[W3C OWL2]
OWL 2 Web Ontology Language: Document Overview, W3C Recommendation.

[W3C SHACL]
Shapes Constraint Language (SHACL), W3C Recommendation.

[OGC GeoSPARQL 1.1]
OGC GeoSPARQL – A Geographic Query Language for RDF Data, OGC Standard.


[W3C vc-data-model-2.0]
Verifiable Credentials Data Model v2.0, W3C Recommendation, May 15 2025.

[W3C vc-data-integrity-1.0]
Verifiable Credential Data Integrity 1.0, W3C Recommendation, May 15 2025.

[W3C controlled-identifiers-1.0]
Controlled Identifiers v1.0, W3C Recommendation, May 15 2025.

[W3C vc-status-list-2021]
Bitstring Status List v1.0, W3C Recommendation, May 15 2025.

[W3C vc-jose-cose]
Securing Verifiable Credentials using JOSE and COSE, W3C Recommendation, May 15 2025.

[W3C OWL-Time]
OWL-Time Ontology, W3C Recommendation.

[schema.org]
Schema.org Core Vocabulary, Schema.org Community Standard.
